version: '2.2'
services:

  flask:
    restart: always
    image: flask_app:latest
    build: .
    networks:
      - external_network
    healthcheck:
        test: curl --fail http://localhost:5000/ping || exit 1
        interval: 10s
        timeout: 2s
        retries: 5
    ports:
      - 5000:80

networks:
  external_network:
    driver: bridge
    ipam:
      driver: default
