version: '2.2'
services:

  flask:
    restart: always
    image: flask_app:latest
    build: .
    networks:
      - external_network
    healthcheck:
        test: curl --fail http://localhost:5000/ping || exit 1
        interval: 10s
        timeout: 2s
        retries: 5
    ports:
      - 5000:80
    volumes:
      - ./example_app:/var/www/app
      - ./flask_app.py:/var/www/app/flask_app.py
      - ./apache2_files/app.wsgi:/var/www/wsgi_scripts/app.wsgi
      - ./apache2_files/app.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache2_files/apache2.conf:/etc/apache2/apache2.conf

networks:
  external_network:
    driver: bridge
    ipam:
      driver: default
